### ISSUE TITLE
Error: Could not find or load main class edu.stanford.nlp.process.PTBTokenizer

### ISSUE THREAD

**Issue by TianlinZhang668** [abisee/cnn-dailymail#28]
i run makedatafiles.py. but it has an error:
Preparing to tokenize /home/ztl/Downloads/cnn_stories/cnn/stories to cnn_stories_tokenized...
Making list of files to tokenize...
Tokenizing 92579 files in /home/ztl/Downloads/cnn_stories/cnn/stories and saving in cnn_stories_tokenized...
Error: Could not find or load main class edu.stanford.nlp.process.PTBTokenizer
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.process.PTBTokenizer
Stanford CoreNLP Tokenizer has finished.
Traceback (most recent call last):

However i can run  echo "Please tokenize this text." | java edu.stanford.nlp.process.PTBTokenizer   in the root
i dont know how to deal with? thanks a lot

**Comment by TianlinZhang668** [comment]
i run the corenlp-3.9.2.jar

**Comment by ubaidsworld** [comment]
You need `stanford-corenlp-3.7.0.jar`. See this: https://github.com/abisee/cnn-dailymail#2-download-stanford-corenlp
Please read the README.md file.

**Comment by 18222278799** [comment]
Preparing to tokenize /home/ztl/Downloads/cnn_stories/cnn/stories to cnn_stories_tokenized...
Making list of files to tokenize...
Tokenizing 92579 files in /home/ztl/Downloads/cnn_stories/cnn/stories and saving in cnn_stories_tokenized...
Traceback (most recent call last):
  File "/home/ztl/PycharmProjects/pointergenerator/make_datafiles.py", line 235, in <module>
    tokenize_stories(cnn_stories_dir, cnn_tokenized_stories_dir)
  File "/home/ztl/PycharmProjects/pointergenerator/make_datafiles.py", line 78, in tokenize_stories
    subprocess.call(command)
  File "/home/ztl/anaconda3/envs/gpu/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/ztl/anaconda3/envs/gpu/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/ztl/anaconda3/envs/gpu/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'


my environment has been setted

**Comment by TianlinZhang668** [comment]
Successfully finished tokenizing /home/ztl/Downloads/cnn_stories/cnn/stories to cnn_stories_tokenized.

Making bin file for URLs listed in url_lists/all_test.txt...
Traceback (most recent call last):
  File "make_datafiles.py", line 239, in <module>
    write_to_bin(all_test_urls, os.path.join(finished_files_dir, "test.bin"))
  File "make_datafiles.py", line 154, in write_to_bin
    url_hashes = get_url_hashes(url_list)
  File "make_datafiles.py", line 106, in get_url_hashes
    return [hashhex(url) for url in url_list]
  File "make_datafiles.py", line 106, in <listcomp>
    return [hashhex(url) for url in url_list]
  File "make_datafiles.py", line 101, in hashhex
    h.update(s)
TypeError: Unicode-objects must be encoded before hashing

i have got the tokenized, but next ....

**Comment by JafferWilson** [comment]
Try this: https://github.com/JafferWilson/Process-Data-of-CNN-DailyMail
Guess it will solve your tokenization and rest other issues.

**Comment by quanghuynguyen1902** [comment]
if I have content of the article that isn't the same as structure of the CNN's article

**Comment by JafferWilson** [comment]
@quanghuynguyen1902 Guess you already have opened a new issue https://github.com/abisee/cnn-dailymail/issues/29
Lets go there. Please someone close this issue.

**Comment by mooncrater31** [comment]
I am facing the same issue in here.

**Comment by SpaceTime1999** [comment]
source ./.bash_profile
