### ISSUE TITLE
byte error while reproducing the processed data 

### ISSUE THREAD

**Issue by Wisharyco** [abisee/cnn-dailymail#30]
While I am processing the data by myself in my local machine, I encountered the following issue: 

Traceback (most recent call last):
  File "make_datafiles.py", line 241, in <module>
    write_to_bin(all_test_urls, os.path.join(finished_files_dir, "test.bin"))
  File "make_datafiles.py", line 186, in write_to_bin
    tf_example.features.feature['article'].bytes_list.value.extend([article])
TypeError: "-lrb- cnn -rrb- -- spirit airlines said thursday it 's sorry that hundreds of passengers had flight has type str, but expected one of: bytes

I indeed modified the code a bit so that I can only process the cnn data (not dm) 
but it seems that the above error does not come from my modification.

Can anybody share your insight with this issue?

**Comment by yooogurt** [comment]
i tried add "article = article.encode()" before this and it worked.
